name: fluttercn
description: FlutterCN 从0到1

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^3.0.3
  fluttertoast: ^3.1.3
  provider: ^3.1.0
  mvvm: ^0.1.7
  json_annotation: ^2.4.0
  webview_flutter: ^0.3.15
  shared_preferences: ^0.5.4
  fluro:
    git: git://github.com/theyakka/fluro.git
  rxdart:
    git: git@github.com:ReactiveX/rxdart.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          style: normal
        - asset: assets/fonts/Quicksand_Bold.otf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Medium.ttf
    - family: WeatherIcon
      fonts:
        - asset: assets/fonts/weather_icon.ttf
